baseURL = "https://flygar.github.io/"
languageCode = "zh-CN"
title = "Flygar's Blog"
theme = "maupassant"
## publishdir = "public"
## canonifyurlsvv= true

[author]
  name = "猪一头"

[params]
  author = "Flygar"
  subtitle = "猪一头"
  keywords = "golang,go语言,go语言笔记"
  description = "我是一头猪"
  busuanzi = true

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 2

[[params.links]]
  title = "flysnow"
  name = "flysnow"
  url = "https://www.flysnow.org"

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

## googleAnalytics = "GA ID"

## 自定义摘要默认是70
summaryLength = 40

## 版权声名
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"
  
## 评论
[params.utteranc]
    enable = true
    repo = "flygar/comments"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

  
