baseURL = "https://flygar.org/"
languageCode = "zh-CN"
title = "Flygar's Blog"
theme = "maupassant"
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止 URL Path 转小写
disablePathToLower = true
## 自定义摘要默认是70
summaryLength = 40

## hasCJKLanguage = true ？？？
### publishdir = "public"
### canonifyurlsvv= true

[author]
  name = "zhutou"

[params]
  author = "Flygar"
  subtitle = "zhutou"
  keywords = "flygar,golang,go语言,go,linux"
  description = "我是一头猪"
  # busuanzi = true # 启用不算子网页统计, 默认false
  localSearch = true # 启用本地搜索
  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  # toc = true  # 是否开启目录, 默认false
  draft = false # 是否作为草稿, 默认true
  # comment = false # 不启用评论系统, 默认true

## 配置网站菜单
[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "comment"
    name = "留言板"
    url = "/comment/"
    weight = 3

## 代码高亮, 更多参考: https://gohugo.io/getting-started/configuration-markup#highlight
[markup]
  [markup.highlight]
    lineNos = false   # 开启行号显示
    style = "github" # 比较中意的样式 rrt, pygments, rainbow_dash, pastie, native, dracula, github, solarized-dark

## 评论
## 配置 utteranc 评论,教程参考 https://utteranc.es/
[params.utteranc]
    enable = true
    repo = "flygar/comments"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 友情连接,可以多个
[[params.links]]
  title = "飞雪无情的博客"
  name = "flysnow"
  url = "https://www.flysnow.org"
[[params.links]]
  title = "昨日当年"
  name = "昨日当年"
  url = "https://zuoridangnian.com"

## 侧边栏广告位, 可以多个
[[params.ads]]
  title = "TripodCloud Network"
  url = "https://clients.tripodcloud.com/aff.php?aff=528"
  img = "https://i.loli.net/2020/03/05/ukL4SFbdYah12em.png"
